-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 13:07:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sinfonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sinfonia` (
  `idsinfonia` INT NOT NULL,
  `data_criacao` DATE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `compositor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsinfonia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orquestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orquestra` (
  `idorquestra` INT NOT NULL,
  `data_criacao` DATE NOT NULL,
  `país` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sinfonia_idsinfonia` INT NOT NULL,
  PRIMARY KEY (`idorquestra`),
  INDEX `fk_orquestra_sinfonia1_idx` (`sinfonia_idsinfonia` ASC) VISIBLE,
  CONSTRAINT `fk_orquestra_sinfonia1`
    FOREIGN KEY (`sinfonia_idsinfonia`)
    REFERENCES `mydb`.`sinfonia` (`idsinfonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcao` (
  `idfuncao` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idfuncao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrumentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrumentos` (
  `idinstrumentos` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinstrumentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`musico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`musico` (
  `cpf` VARCHAR(11) NOT NULL,
  `nacionalidade` VARCHAR(15) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sinfonia_idsinfonia` INT NOT NULL,
  `orquestra_idorquestra` INT NOT NULL,
  `funcao_idfuncao` INT NOT NULL,
  `instrumentos_idinstrumentos` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_musico_sinfonia_idx` (`sinfonia_idsinfonia` ASC) VISIBLE,
  INDEX `fk_musico_orquestra1_idx` (`orquestra_idorquestra` ASC) VISIBLE,
  INDEX `fk_musico_funcao1_idx` (`funcao_idfuncao` ASC) VISIBLE,
  INDEX `fk_musico_instrumentos1_idx` (`instrumentos_idinstrumentos` ASC) VISIBLE,
  CONSTRAINT `fk_musico_sinfonia`
    FOREIGN KEY (`sinfonia_idsinfonia`)
    REFERENCES `mydb`.`sinfonia` (`idsinfonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_musico_orquestra1`
    FOREIGN KEY (`orquestra_idorquestra`)
    REFERENCES `mydb`.`orquestra` (`idorquestra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_musico_funcao1`
    FOREIGN KEY (`funcao_idfuncao`)
    REFERENCES `mydb`.`funcao` (`idfuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_musico_instrumentos1`
    FOREIGN KEY (`instrumentos_idinstrumentos`)
    REFERENCES `mydb`.`instrumentos` (`idinstrumentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
