-- MySQL Script generated by MySQL Workbench
-- Fri Oct 18 17:05:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Composicao_sinfonica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Composicao_sinfonica` (
  `idSinfonia` INT NOT NULL,
  `data_composta` DATE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `compositor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSinfonia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orquestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orquestra` (
  `idOrquestra` INT NOT NULL,
  `data_criacao` DATE NOT NULL,
  `país` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrquestra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcao` (
  `idFuncao` INT NOT NULL,
  `descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instrumento_musical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instrumento_musical` (
  `idInstrumento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstrumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Musico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Musico` (
  `cpf` INT NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `Sinfonia_idSinfonia` INT NOT NULL,
  `Orquestra_idOrquestra` INT NOT NULL,
  `Funcao_idFuncao` INT NOT NULL,
  `Instrumento_idInstrumento` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_Musico_Composicao_sifonica_idx` (`Sinfonia_idSinfonia` ASC) VISIBLE,
  INDEX `fk_Musico_Orquestra1_idx` (`Orquestra_idOrquestra` ASC) VISIBLE,
  INDEX `fk_Musico_Funcao1_idx` (`Funcao_idFuncao` ASC) VISIBLE,
  INDEX `fk_Musico_Instrumento_musical1_idx` (`Instrumento_idInstrumento` ASC) VISIBLE,
  CONSTRAINT `fk_Musico_Composicao_sifonica`
    FOREIGN KEY (`Sinfonia_idSinfonia`)
    REFERENCES `mydb`.`Composicao_sinfonica` (`idSinfonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musico_Orquestra1`
    FOREIGN KEY (`Orquestra_idOrquestra`)
    REFERENCES `mydb`.`Orquestra` (`idOrquestra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musico_Funcao1`
    FOREIGN KEY (`Funcao_idFuncao`)
    REFERENCES `mydb`.`Funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musico_Instrumento_musical1`
    FOREIGN KEY (`Instrumento_idInstrumento`)
    REFERENCES `mydb`.`Instrumento_musical` (`idInstrumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
